language: android

android:
  components:
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository

# Override the install and test so that we don't run integration tests
install:
  - ./gradlew androidDependencies
  - ./gradlew assemble --stacktrace

script:
  - ./gradlew :hurryporter:test -i